### ISSUE TITLE
Doesn't seem to work anymore

### ISSUE THREAD

**Issue by adamreisnz** [IgorKvasn/ember-vendor-analyzer#1]
Analysing our 7mb vendor.js file, all I get out of it with this tool is one package:

```
pretender - size= 3069023 B / 2997 kB
```

**Comment by IgorKvasn** [comment]
yeah, you are right - I might look at it this weekend

**Comment by cbou** [comment]
I got this error

```
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: -1, Size: 0
	at java.util.LinkedList.checkElementIndex(LinkedList.java:555)
	at java.util.LinkedList.get(LinkedList.java:476)
	at sk.Main.doIt(Main.java:43)
	at sk.Main.main(Main.java:79)
```
